### ISSUE TITLE
Unit of measure of the Road Length

### ISSUE THREAD

**Issue by JuanRFernandez** [JoaoCarabetta/osmpy#2]
* Python version: 3.10
* Operating System: Windows

### Description

Hi, I am measuring the total length of road networks and I would kindly ask you what is the unit of measure of the length given by the "osmpy.get('RoadLength', boundary)" function. It is in meters? km?  

Thank you, 
Juan

**Comment by JoaoCarabetta** [comment]
That is indeed a good question.

The docstring says:

```python
def get(query, boundary, threshold_value=1000000, urllen_threshold=7648):
    """Get Open Street Maps highways length in meters and object count for a given boundary

    It splits the regions to manage overpass turbo limits.

    For MultiPolygons, only the biggest polygon will be considered.
```

So it is meters. 

I'll make it explicit in the README
